on:
  workflow_dispatch:
  schedule:
     - cron: "15 18 * * *"
  
  
name: get_elim_drafts

jobs:
  elim_drafts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
      MFL_CLIENT: ${{ secrets.MFL_CLIENT }}
      MFL_USER_ID: ${{ secrets.MFL_USER_ID }}
      MFL_PWD: ${{ secrets.PWD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: ffscrapr, dplyr, data.table, tidyr, purrr, stringr, piggyback, cli, readr, lubridate
        name: Run data update
      - run: |
          source("get_FCELIM_drafts.R")
        shell: Rscript {0}
