on:
  workflow_dispatch:
  schedule:
     - cron: "0 7 * * *"
  
  
name: get_completed_elim_drafts

jobs:
  elim_drafts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
      MFL_CLIENT: ${{ secrets.MFL_CLIENT }}
      MFL_USER_ID: ${{ secrets.MFL_USER_ID }}
      MFL_PWD: ${{ secrets.PWD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: ffscrapr, data.table, nflverse, stringr, lubridate, piggyback, readr, dplyr, tidyr, tidyverse, purrr, cli
        name: Run data update
      - run: |
          source("generate_FCELIM_completed.R")
        shell: Rscript {0}
